import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getCurrentUser } from "@/lib/auth/session";
import { getOnboarding } from "@/lib/data/onboarding";
import {
  getSummary,
  getTimeline,
  getFrequencyByMonth,
} from "@/lib/mock/health";
import { CARE_CONTEXTS } from "@/lib/validation/onboarding";

// Generates a shareable PDF "appointment record" for the logged-in user.
// Data is currently the mock summary; the structure matches the future
// structured-memory source.
export async function GET() {
  const user = await getCurrentUser();
  if (!user) {
    return new Response("Unauthorized", { status: 401 });
  }

  const profile = getOnboarding(user.id);
  const summary = getSummary();
  const timeline = getTimeline();
  const frequency = getFrequencyByMonth();

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const ink = rgb(0.1, 0.11, 0.1);
  const muted = rgb(0.42, 0.44, 0.43);
  const accent = rgb(0.055, 0.486, 0.4);
  const margin = 56;
  let y = 786;

  const text = (s, x, yy, { size = 11, f = font, color = ink } = {}) =>
    page.drawText(String(s), { x, y: yy, size, font: f, color });

  // Header
  text("Health Companion", margin, y, { size: 20, f: bold, color: accent });
  text("Appointment record", margin, y - 22, { size: 12, f: bold });
  text(
    `Generated on ${new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })}`,
    margin,
    y - 40,
    { size: 10, color: muted },
  );
  page.drawLine({
    start: { x: margin, y: y - 52 },
    end: { x: 539, y: y - 52 },
    thickness: 1,
    color: rgb(0.89, 0.9, 0.89),
  });
  y -= 78;

  // Profile
  const careLabel =
    CARE_CONTEXTS.find((c) => c.value === profile?.careContext)?.label || "—";
  text("Profile", margin, y, { size: 13, f: bold });
  y -= 20;
  const rows = [
    ["Name", profile?.preferredName || user.name || "—"],
    ["Pronouns", profile?.pronouns || "—"],
    ["Journey", careLabel],
    ["Therapy start", profile?.therapyStartDate || "—"],
  ];
  for (const [k, v] of rows) {
    text(k, margin, y, { size: 10, color: muted });
    text(v, margin + 130, y, { size: 11 });
    y -= 18;
  }
  y -= 14;

  // Summary
  text("Summary", margin, y, { size: 13, f: bold });
  y -= 20;
  text(
    `Check-ins logged: ${summary.checkins}   ·   Tracked symptoms: ${summary.trackedSymptoms}   ·   Last: ${summary.lastCheckin}`,
    margin,
    y,
    { size: 11 },
  );
  y -= 30;

  // Frequency table
  text("Days with symptoms per month", margin, y, { size: 13, f: bold });
  y -= 20;
  for (const row of frequency) {
    text(row.month, margin, y, { size: 10, color: muted });
    const barW = row.days * 8;
    page.drawRectangle({
      x: margin + 60,
      y: y - 2,
      width: barW,
      height: 9,
      color: accent,
    });
    text(`${row.days} d`, margin + 64 + barW, y, { size: 9, color: muted });
    y -= 18;
  }
  y -= 14;

  // Timeline
  text("Recent events", margin, y, { size: 13, f: bold });
  y -= 20;
  for (const item of timeline) {
    text(item.date, margin, y, { size: 10, f: bold, color: accent });
    text(item.text, margin + 60, y, { size: 10 });
    y -= 18;
  }

  // Footer
  text(
    "Generated by your health companion. This is not a substitute for medical advice.",
    margin,
    48,
    { size: 8, color: muted },
  );

  const bytes = await pdf.save();
  return new Response(bytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="companion-report.pdf"',
    },
  });
}
