// Custom Worker entrypoint. Wraps the OpenNext-generated handler and re-exports
// our Durable Object so wrangler can bind the `BackendDO` class.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.

// @ts-ignore generated at build time
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
};

export { BackendDO } from "./src/backend/do.js";
